name: apiverve_anagrampuzzle
description: Anagram Puzzle Generator creates word puzzles where players rearrange scrambled letters to form valid words, with optional hints.
version: 1.1.14
homepage: https://apiverve.com/marketplace/anagrampuzzle?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/anagrampuzzle-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
